/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Stages', [{
      stageName: 'Новые',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Назначено видеоинтервью',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Резюме передано заказчику',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Назначено интервью',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Назначен звонок',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Выставлен оффер',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Принял офер',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Выход на работу',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      stageName: 'Отказ',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});

    await queryInterface.bulkInsert('Users', [{
      userName: 'Антон',
      userEmail: 'anton88@yandex.ru',
      password: '$2b$10$eKeSzgpD2YsiICuvrJGX7ugkt6vdMh9cv4JPKzE6qDhpt23Og3I9O',
      userPhoto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Steve_Buscemi_%281996%29.jpg/220px-Steve_Buscemi_%281996%29.jpg',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});

    await queryInterface.bulkInsert('Applicants', [{
      applPhoto: 'public/files/photo/73f8d9768cca453f965ab7a3f3837053',
      applName: 'Мария',
      applLastName: 'Иванова',
      experience: '3',
      phone: '89113251678',
      applEmail: 'mary@gmail.com',
      pdf: 'https://binaries.templates.cdn.office.net/support/templates/ru-ru/lt16402487_quantized.png',
      position: 'Frontend-разработчик',
      wage: '120000',
      location: 'Уренгой',
      about: 'Опытная, приятная в общении.',
      stageId: 5,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/3c4feaae9f07528a0efa36c824a79f02',
      applName: 'Иван',
      applLastName: 'Масков',
      experience: '10',
      phone: '89213256628',
      applEmail: 'mask@gmail.com',
      position: 'Инженер',
      wage: '150000',
      location: 'Луга',
      about: 'Оставляет впечатление очень умного человека.',
      stageId: 1,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/97db814065b2d0d4c68c09d845d9da51',
      applName: 'Евгений',
      applLastName: 'Маэстров',
      experience: '5',
      phone: '89992489032',
      applEmail: 'maestro@gmail.com',
      position: 'Маркетолог',
      wage: '200000',
      location: 'Санкт-Петергбург',
      about: 'Неотразимая энергетика.',
      stageId: 2,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/25caf9161ed7e5e86fcb8b1031bf9fa0',
      applName: 'Ника',
      applLastName: 'Чашева',
      experience: '2',
      phone: '89283652215',
      applEmail: 'nixpix@gmail.com',
      position: 'Backend-разработчик',
      wage: '80000',
      location: 'Ростов',
      about: 'Сильная женщина.',
      stageId: 3,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/c6515245f57f8282bc7f46243006fb1b',
      applName: 'Кристиан',
      applLastName: 'Белов',
      experience: '10',
      phone: '89256714402',
      applEmail: 'american@gmail.com',
      position: 'Backend-разработчик',
      wage: '160000',
      location: 'Санкт-Петербург',
      about: 'Умеет показать себя, отличная визитка.',
      stageId: 4,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/c5ed995566824c313f5688ac8c9ddfbb',
      applName: 'Екатерина',
      applLastName: 'Амур',
      experience: '1',
      phone: '89996916920',
      applEmail: 'amouranth@gmail.com',
      position: 'Q&A',
      wage: '300000',
      location: 'Москва',
      about: 'У Екатерины очень большие таланты.',
      stageId: 5,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/5224775e260481389abb18d24d3814b3',
      applName: 'Герман',
      applLastName: 'Петров',
      experience: '30',
      phone: '89613456612',
      applEmail: 'garold@gmail.com',
      position: 'Уборщик',
      wage: '15000',
      location: 'Москва',
      about: 'Позитивный человек.',
      stageId: 6,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/49d48dbdcc8c0f705eed43de0ff68bc8',
      applName: 'Илья',
      applLastName: 'Меддисонович',
      experience: '15',
      phone: '89215553476',
      applEmail: 'lovehovan@gmail.com',
      position: 'Q&A',
      wage: '150000',
      location: 'Москва',
      about: 'Очень хорошие рекомендации.',
      stageId: 7,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/42cdeee023412d99f41a9c2aaeb7f8d2',
      applName: 'Александр',
      applLastName: 'Курицын',
      experience: '15',
      phone: '89283472210',
      applEmail: 'universe@gmail.com',
      position: 'Рекламное лицо',
      wage: '70000',
      location: 'Москва',
      about: 'Есть рекомендация от Евгения Баженова.',
      stageId: 8,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      applPhoto: 'public/files/photo/d37658ba7cc5aecb10264128c2bd86e5',
      applName: 'Александр',
      applLastName: 'Узкий',
      experience: '10',
      phone: '89993567012',
      applEmail: 'gudok@gmail.com',
      position: 'Агент',
      wage: '160000',
      location: 'Санкт-Петербург',
      about: 'Хорошее чувство юмора.',
      stageId: 9,
      userId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Applicants', null, {});
    await queryInterface.bulkDelete('Users', null, {});
    await queryInterface.bulkDelete('Stages', null, {});
  },
};
